# Site settings
title: Miami Mobile Devs 
email: jpere268@fiu.edu
description: > # this means to ignore newlines until "baseurl:"
       Miami Mobile Devs Blog and News 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://miamimobiledevs.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  MiamiMobileDevs

# Build settings
markdown: kramdown
